### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by glauberramos** [glauberramos/psideborahmazeron#1]
- [ ] Link para abrir whatsapp no celular
- [ ] Adicionar posts restantes
- [ ] Adicionar links informativos resolucao
- [ ] Adicionar numero cpt algo assim
- [ ] Arrumar logo fundo branco
- [ ] Ver como fazer lista gratis de email
- [ ] Adicionar link zenklub
- [ ] Preencher info sobre atendimento
- [ ] Preencher info pagina sobre
- [ ] Adicionar analytics
- [ ] Mobile design
- [ ] Adicionar endereço
